version: '3.7'

services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    depends_on:
      - mongodb
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
      - DATABASE_URL=mongodb://mongodb:27017/instagram_clone

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=instagram_clone
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=vanhvanh
